Add `tfschema`
cloudposse/packages pull request #1545
Opened 2021-07-30 04:13 UTC by nitrocode

## what
* Add `tfschema`

## why
* A schema inspector for Terraform providers

## references
* https://github.com/minamijoyo/tfschema
* Closes https://github.com/cloudposse/packages/issues/1541

## commands

```shell
make init
make readme
make -C .github workflows
make -C vendor/tfschema install
make -C vendor/tfschema test
```

2021-07-30 06:02 UTC, Nuru requested changes

2021-07-30 06:02 UTC, Nuru commented on vendor/tfschema/Makefile
> +export CHECK_COMMAND_ENV ?= HOME=./
I don't know where these `CHECK_COMMAND` env vars came from, but they are not used.

Use `APKBUILD_DEPENDS` to support package that needs extra libraries for Alpine
```suggestion
export APKBUILD_DEPENDS += libc6-compat
```

2021-07-30 11:58 UTC, nitrocode commented on apk/Dockerfile-alpine
> +    apk add make curl alpine-sdk shadow bash jq sudo go libc6-compat
If this is removed then tfschema doesn't build for alpine. Is there an alternative to only add the libc6-compat package when building tfschema?

2021-07-30 12:02 UTC, nitrocode commented on apk/Dockerfile-alpine
> +    apk add make curl alpine-sdk shadow bash jq sudo go libc6-compat
Nevermind I just saw the other comment. Thank you!

2021-07-31 15:53 UTC, Nuru approved these changes

2021-07-31 15:53 UTC, merged