packages: add amazon-ecr-credential-helper
cloudposse/packages pull request #2052
Opened 2022-01-25 17:25 UTC by leb4r

## what

* Adds `amazon-ecr-credential-helper`  

## why

*  Use AWS credentials to perform actions against ECR

2022-01-25 17:33 UTC, nitrocode commented
Added references. Looks good to me. Maybe get one more approval though.

cc: @Nuru @aknysh

2022-01-25 17:33 UTC, nitrocode submitted a review, later dismissed

2022-01-25 17:34 UTC, nitrocode commented
Hmmm actually on second thought, it looks like the docs weren't updated

2022-01-25 17:47 UTC, nitrocode approved these changes
Added references. Looks good to me. Maybe get one more approval though.

cc: @Nuru @aknysh

2022-01-26 19:48 UTC, Nuru requested changes

2022-01-26 19:48 UTC, Nuru commented on vendor/amazon-ecr-credential-helper/Makefile
> +	HOME=/tmp $(PACKAGE_EXE) version
Doesn't work that way, plus we check the version number if possible
```suggestion
	HOME=/tmp $(PACKAGE_EXE) -v | grep -F $(PACKAGE_VERSION)
```

2022-01-26 20:02 UTC, Nuru commented
Remember to `make readme` after any changes. I prefer to do it under Docker:

```
make docker/build/deb/shell
make readme
exit
```

2022-01-26 20:25 UTC, leb4r commented on vendor/amazon-ecr-credential-helper/Makefile
> +export PACKAGE_NAME ?= docker-credential-ecr-login
@Nuru I believe this is consistent elsewhere I've used it (see their [readme](https://github.com/awslabs/amazon-ecr-credential-helper#prerequisites)), where the package is named `amazon-ecr-credential-helper` but it installs `docker-credential-ecr-login` binary. 

Docker uses the prefix `docker-credential-*` as a means to search out the credential helpers on the system. 

Is there a better way to get the same results?

2022-01-26 20:54 UTC, Nuru commented on vendor/amazon-ecr-credential-helper/Makefile
> +export PACKAGE_NAME ?= docker-credential-ecr-login
The `PACKAGE_NAME` is the name we are giving to the package in the package repo, e.g. `apt-get install $PACKAGE_NAME`.

2022-01-26 20:55 UTC, Nuru commented on vendor/amazon-ecr-credential-helper/Makefile
> +export PACKAGE_NAME ?= docker-credential-ecr-login
The installed file will still be `$PACKAGE_EXE`, which is `docker-credential-ecr-login`

2022-01-26 21:03 UTC, Nuru approved these changes

2022-01-26 22:06 UTC, merged