Update `stern` repo
cloudposse/packages pull request #3085
Opened 2022-11-19 01:05 UTC by aknysh

## what
* Update `stern` repo
* Update GitHub workflows

## why
* Update `stern` repo from https://github.com/wercker/stern (which has been deleted) to https://github.com/stern/stern
* Keep GitHub workflows and READMEs up to date

2022-11-19 01:15 UTC, nitrocode approved these changes

2022-11-20 18:26 UTC, Nuru requested changes

2022-11-20 18:26 UTC, Nuru commented on .github/workflows/validate-codeowners.yml
Revert

2022-11-20 18:26 UTC, Nuru commented on .github/workflows/validate-codeowners.yml
> +        owner_checker_allow_unowned_patterns: "false"
Revert

2022-11-20 18:26 UTC, Nuru commented on vendor/stern/VERSION
> +1.22.0
Do we want to release any intermediate versions?

2022-11-20 18:29 UTC, Nuru submitted a review, later dismissed
Revert automatic changes that were meant for Terraform modules and should not be made here.

2022-11-21 16:48 UTC, osterman approved these changes

2022-11-21 16:58 UTC, merged