feat(aws): add aws-nuke and cloud-nuke
cloudposse/packages pull request #3187
Opened 2022-12-21 16:32 UTC by dudymas

## what
* add aws-nuke
* add cloud-nuke

## why
* both provide opinionated ways for clearing aws accounts
* cloud-nuke can be appropriate for a one-off account that does not serve a tier1 (ie prod) purpose
* aws-nuke can be appropriate for tier1 accounts where multiple accounts are expected for a root/superadmin

## references
* https://github.com/gruntwork-io/cloud-nuke
* https://github.com/rebuy-de/aws-nuke

2022-12-23 04:35 UTC, nitrocode commented on vendor/cloud-nuke/Makefile
> +#export APKBUILD_DEPENDS += # add dependencies here
```suggestion
```

2022-12-23 04:36 UTC, nitrocode requested changes
This won't work as is because the github actions have not been generated. 

Please look at commands in this pr.

https://github.com/cloudposse/packages/pull/2430

2022-12-23 04:55 UTC, nitrocode commented on vendor/aws-nuke/Makefile
> +#export APKBUILD_DEPENDS += # add dependencies here
```suggestion
```

2022-12-23 05:10 UTC, dudymas commented on vendor/aws-nuke/Makefile
> +#export APKBUILD_DEPENDS += # add dependencies here
fixed

2022-12-23 05:18 UTC, dudymas commented
@nitrocode thanks! I think I figured out what was unhappy. I'll mention in channel once this is all green

2022-12-28 16:20 UTC, osterman approved these changes

2022-12-29 01:40 UTC, nitrocode approved these changes

2022-12-29 01:40 UTC, merged