terraform-0.14 package added
cloudposse/packages pull request #692
Opened 2020-11-23 20:21 UTC by maximmi

## what
* terraform 0.14-rc1 added

## why
* to be able to start using and testing modules with 0.14 version

2020-11-23 20:31 UTC, Nuru requested changes
Do not create a `terraform_0.14` package. The packages with underscores are obsolete, we maintain the existing ones for people who use them, but we encourage everyone to switch to the packages with dashes.

2020-11-23 20:31 UTC, Nuru commented on vendor/terraform-0.14/Makefile
> +export AUTO_UPDATE_ENABLED = false
```suggestion
```

2020-11-23 20:31 UTC, Nuru commented on vendor/terraform-0.14/Makefile
> +export MAJOR_VERSION = 0.14
```suggestion
export MAJOR_VERSION = 0.14
export PACKAGE_PRERELEASE_ENABLED = true
```

2020-11-23 20:31 UTC, Nuru commented on vendor/terraform-0.14/terraform_0.14.post-deinstall
> +update-alternatives --remove ${MASTER_PACKAGE_NAME} ${INSTALL_DIR}/${PACKAGE_NAME} --quiet
```suggestion
update-alternatives --remove ${PACKAGE_NAME} ${INSTALL_DIR}/${MASTER_PACKAGE_NAME} --quiet
update-alternatives --remove ${PACKAGE_NAME}-direnv ${INSTALL_DIR}/${MASTER_PACKAGE_NAME} --quiet
update-alternatives --remove ${MASTER_PACKAGE_NAME} ${INSTALL_DIR}/${MASTER_PACKAGE_NAME} --quiet
```

2020-11-23 20:48 UTC, maximmi commented on vendor/terraform-0.14/Makefile
> +export MAJOR_VERSION = 0.14
done

2020-11-24 05:25 UTC, osterman submitted a review, later dismissed

2020-11-24 07:52 UTC, Nuru submitted a review, later dismissed

2020-11-24 08:58 UTC, Nuru approved these changes

2020-11-24 08:59 UTC, merged